apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservicedb-deployment
spec:
  replicas: 1  # Number of PostgreSQL pods
  selector:
    matchLabels:
      app: identityservicedb
  template:
    metadata:
      labels:
        app: identityservicedb
    spec:
      containers:
      - name: postgres
        image: postgres:latest  # PostgreSQL image
        env:
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "identityservicedb"
        ports:
        - containerPort: 5434  # PostgreSQL port
        volumeMounts:
        - name: identityservicedb-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: identityservicedb-data
        persistentVolumeClaim:
          claimName: identityservicedb-pvc  # Reference to Persistent Volume Claim
