apiVersion: v1
kind: Service
metadata:
  name: identityservicedb-service
spec:
  selector:
    app: identityservicedb
  ports:
    - protocol: TCP
      port: 5434  # PostgreSQL port
      targetPort: 5432  # Target port on the pod
  type: ClusterIP  # Use NodePort or LoadBalancer for external access