apiVersion: v1
kind: Service
metadata:
  name: contentservicedb-service
spec:
  selector:
    app: contentservicedb
  ports:
    - protocol: TCP
      port: 5432  # PostgreSQL port
      targetPort: 5432  # Target port on the pod
  type: ClusterIP  # Use NodePort or LoadBalancer for external access