apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentservicedb-deployment
spec:
  replicas: 1  # Number of PostgreSQL pods
  selector:
    matchLabels:
      app: contentservicedb
  template:
    metadata:
      labels:
        app: contentservicedb
    spec:
      containers:
      - name: postgres
        image: postgres:latest  # PostgreSQL image
        env:
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "contentservicedb"
        ports:
        - containerPort: 5432  # PostgreSQL port
        volumeMounts:
        - name: contentservicedb-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: contentservicedb-data
        persistentVolumeClaim:
          claimName: contentservicedb-pvc
