apiVersion: v1
kind: Secret
metadata:
  name: contentservice-postgres-credentials
type: Opaque
data:
  connectionString: SG9zdD1jb250ZW50c2VydmljZWRiLXNlcnZpY2U7UG9ydD01NDMyO1VzZXJuYW1lPXVzZXJuYW1lO1Bhc3N3b3JkPXBhc3N3b3JkMTIzO0RhdGFiYXNlPWNvbnRlbnRzZXJ2aWNlZGI7

---

apiVersion: v1
kind: Secret
metadata:
  name: contentservice-postgres-credentials-azure
type: Opaque
data:
  connectionString: aHR0cHM6Ly9rdi1pbmRpdmlkdWFsLWV1dy52YXVsdC5henVyZS5uZXQvc2VjcmV0cy9jb250ZW50c2VydmljZWRiLWNvbm5lY3Rpb25zdHJpbmcvNWYyYzlhNGU1MzI1NGQyMzk5ZWVmMTYyZjgzZGVlMjE=