apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        #image: k3d-fontys:5000/frontend:v0.1
        image: niielsss/individual-s6-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
