apiVersion: v1
kind: Service
metadata:
  name: reviewservicedb-service
spec:
  selector:
    app: reviewservicedb
  ports:
    - protocol: TCP
      port: 5433  # PostgreSQL port
      targetPort: 5432  # Target port on the pod
  type: ClusterIP  # Use NodePort or LoadBalancer for external access