apiVersion: v1
kind: Secret
metadata:
  name: reviewservice-postgres-credentials
type: Opaque
data:
  connectionString: SG9zdD1yZXZpZXdzZXJ2aWNlZGItc2VydmljZTtQb3J0PTU0MzM7VXNlcm5hbWU9dXNlcm5hbWU7UGFzc3dvcmQ9cGFzc3dvcmQxMjM7RGF0YWJhc2U9cmV2aWV3c2VydmljZWRiOw==