apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reviewservicedb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Amount of storage you require