apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservicedb-deployment
spec:
  replicas: 1  # Number of PostgreSQL pods
  selector:
    matchLabels:
      app: reviewservicedb
  template:
    metadata:
      labels:
        app: reviewservicedb
    spec:
      containers:
      - name: postgres
        image: postgres:latest  # PostgreSQL image
        env:
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "reviewservicedb"
        ports:
        - containerPort: 5433  # PostgreSQL port
        volumeMounts:
        - name: reviewservicedb-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: reviewservicedb-data
        persistentVolumeClaim:
          claimName: reviewservicedb-pvc  # Reference to Persistent Volume Claim
